{"name":"CheckingfailedTest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Expected to fail`","trace":"java.lang.AssertionError: Expected to fail`\n\tat org.testng.Assert.fail(Assert.java:97)\n\tat QuickTests.CheckingfailedTest(QuickTests.java:69)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1507)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:766)\n\tat org.testng.TestRunner.run(TestRunner.java:587)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1109)\n\tat org.testng.TestNG.runSuites(TestNG.java:1039)\n\tat org.testng.TestNG.run(TestNG.java:1007)\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\n"},"stage":"finished","description":"To check failed test case","steps":[],"attachments":[{"name":"saveFailureScreenshot","source":"39a8e960-e82e-4ee2-b670-f9dbf4612be3-attachment"},{"name":"CheckingfailedTest is failed and screenshot is taken","source":"8f4cb910-2a3b-4365-a70c-1555ba5ef61a-attachment","type":"text/plain"}],"parameters":[],"start":1583783728251,"stop":1583783729128,"uuid":"1fa304ed-ed1b-4e94-874d-a836cd4deb1d","historyId":"716ebd7682a0a629c2c9254e60672c31","fullName":"QuickTests.CheckingfailedTest","labels":[{"name":"package","value":"QuickTests"},{"name":"testClass","value":"QuickTests"},{"name":"testMethod","value":"CheckingfailedTest"},{"name":"parentSuite","value":"Sample Programmes"},{"name":"suite","value":"QuickTests"},{"name":"subSuite","value":"QuickTests"},{"name":"host","value":"Sirajs-MacBook-Air.local"},{"name":"thread","value":"40632@Sirajs-MacBook-Air.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"minor"}],"links":[]}