<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-03-09T15:55:12 EDT" name="Sample Programmes" finished-at="2020-03-09T15:55:29 EDT" duration-ms="16526">
    <groups>
      <group name="now">
        <method signature="QuickTests.screenshotOfPage()[pri:0, instance:QuickTests@60e9df3c]" name="screenshotOfPage" class="QuickTests"/>
        <method signature="QuickTests.screenshotOfaSectionOnAPage()[pri:0, instance:QuickTests@60e9df3c]" name="screenshotOfaSectionOnAPage" class="QuickTests"/>
      </group> <!-- now -->
    </groups>
    <test started-at="2020-03-09T15:55:12 EDT" name="QuickTests" finished-at="2020-03-09T15:55:29 EDT" duration-ms="16526">
      <class name="QuickTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:QuickTests@60e9df3c]" started-at="2020-03-09T15:55:12 EDT" name="setup" finished-at="2020-03-09T15:55:22 EDT" duration-ms="9391" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="screenshotOfPage()[pri:0, instance:QuickTests@60e9df3c]" started-at="2020-03-09T15:55:22 EDT" name="screenshotOfPage" description="Selenium features taking screenshot of a page" finished-at="2020-03-09T15:55:26 EDT" duration-ms="4256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOfPage -->
        <test-method signature="screenshotOfaSectionOnAPage()[pri:0, instance:QuickTests@60e9df3c]" started-at="2020-03-09T15:55:26 EDT" name="screenshotOfaSectionOnAPage" finished-at="2020-03-09T15:55:28 EDT" duration-ms="1478" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOfaSectionOnAPage -->
        <test-method signature="CheckingfailedTest()[pri:5, instance:QuickTests@60e9df3c]" started-at="2020-03-09T15:55:28 EDT" name="CheckingfailedTest" finished-at="2020-03-09T15:55:28 EDT" duration-ms="8" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected to fail`]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected to fail`
at org.testng.Assert.fail(Assert.java:97)
at QuickTests.CheckingfailedTest(QuickTests.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckingfailedTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:QuickTests@60e9df3c]" started-at="2020-03-09T15:55:29 EDT" name="tearDown" finished-at="2020-03-09T15:55:29 EDT" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- QuickTests -->
    </test> <!-- QuickTests -->
  </suite> <!-- Sample Programmes -->
</testng-results>
